# This file is a model of Django-Stubs configuration in pyproject.toml

# Django static type checker:
[tool.mypy]
...
plugins = ["mypy_django_plugin.main"]

# Django-stubs plugin configuration
[tool.django-stubs]
django_settings_module = "core.settings"