# This file is a model of Django-Stubs configuration in pyproject.toml

# Python static type checker:
[tool.mypy]
...
plugins = [
    "mypy_django_plugin.main", # Adding Type checking for Django too.
]
disable_error_code = [
    "var-annotated",  # Stop MyPy to demand Type Annotations for, e.g., model fields w/ M2M relationships.
]

# Django-stubs plugin configuration
[tool.django-stubs]
django_settings_module = "core.settings"