from django.db import models


# Create your models here.
class Movie(models.Model):
    name = ...
    released_year = ...
    director = ...
    rating = ...

    def __str__(self):
        return f'{self.name} ({self.released_year})'
