# This file is a model of MyPy configuration in pyproject.toml

# Python static type checker:
[tool.mypy]
python_version = "3.13"  # IS THIS RIGHT???????????????????????????
check_untyped_defs = true
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
strict_optional = true
show_error_codes = true
plugins = []
disable_error_code = []
exclude = [
    "migrations/",
    "venv/",
    ".venv/",
    ".vscode",
    "frontend/",
    "templates/",
    "static",
    "media",
]
[[tool.mypy.overrides]]  # Django-specific mypy settings
module = "*.migrations.*"
ignore_errors = true