lang = {
    "English": [
        'that', 'with', 'from', 'this', 'they', 'will', 'would', 'about', 'their', 'there', 'what',
        'which', 'when', 'make', 'time', 'just', 'know', 'take', 'people', 'into', 'year', 'your',
        'good', 'some', 'could', 'them', 'other', 'than', 'then', 'look', 'only', 'come', 'over',
        'think', 'also', 'back', 'after', 'work', 'first', 'well', 'even', 'want', 'because', 'these',
        'give', 'most', 'thing', 'such', 'tell', 'many', 'very', 'find', 'here', 'being', 'before',
        'between', 'must', 'where', 'right', 'through', 'around', 'today', 'different', 'without',
        'should', 'place', 'every', 'under', 'small', 'found', 'still', 'under', 'part', 'home',
        'during', 'another', 'large', 'learn', 'always', 'until', 'night', 'along', 'follow', 'problem',
        'begin', 'might', 'water', 'often', 'together', 'family', 'direct', 'leave', 'measure', 'door',
        'product', 'black', 'short', 'digit', 'class', 'wind', 'question', 'happen', 'complete',
        'ship', 'area', 'half', 'rock', 'order', 'fire', 'south', 'problem', 'piece', 'told', 'knew',
        'pass', 'since', 'top', 'whole', 'king', 'space', 'heard', 'best', 'hour', 'better', 'true',
        'during', 'hundred', 'remember', 'step', 'early', 'hold', 'west', 'ground', 'interest',
        'reach', 'fast', 'verb', 'sing', 'listen', 'six', 'table', 'travel', 'less', 'morning',
        'ten', 'simple', 'several', 'vowel', 'toward', 'war', 'lay', 'against', 'pattern', 'slow',
        'center', 'love', 'person', 'money', 'serve', 'appear', 'road', 'map', 'rain', 'rule',
        'govern', 'pull', 'cold', 'notice', 'voice', 'unit', 'power', 'town', 'fine', 'certain',
        'fly', 'fall', 'lead', 'cry', 'dark', 'machine', 'note', 'wait', 'plan', 'figure', 'star',
        'box', 'noun', 'field', 'rest', 'correct', 'able', 'pound', 'done', 'beauty', 'drive',
        'stood', 'contain', 'front', 'teach', 'week', 'final', 'gave', 'green', 'quick', 'develop',
        'ocean', 'warm', 'free', 'minute', 'strong', 'special', 'mind', 'behind', 'clear', 'tail',
        'produce', 'fact', 'street', 'inch', 'multiply', 'nothing', 'course', 'stay', 'wheel',
        'full', 'force', 'blue', 'object', 'decide', 'surface', 'deep', 'moon', 'island', 'foot',
        'system', 'busy', 'test', 'record', 'boat', 'common', 'gold', 'possible', 'plane', 'stead',
        'dry', 'wonder', 'laugh', 'thousand', 'ago', 'ran', 'check', 'game', 'shape', 'equate',
        'hot', 'miss', 'brought', 'heat', 'snow', 'tire', 'bring', 'yes', 'distant', 'fill', 'east',
        'paint', 'language', 'among', 'grand', 'ball', 'yet', 'wave', 'drop', 'heart', 'present',
        'heavy', 'dance', 'engine', 'position', 'arm', 'wide', 'sail', 'material', 'size', 'vary',
        'settle', 'speak', 'weight', 'general', 'ice', 'matter', 'circle', 'pair', 'include',
        'divide', 'syllable', 'felt', 'perhaps', 'pick', 'sudden', 'count', 'square', 'reason',
        'length', 'represent', 'art', 'subject', 'region', 'energy', 'hunt', 'probable', 'bed',
        'brother', 'egg', 'ride', 'cell', 'believe', 'fraction', 'forest', 'sit', 'race', 'window',
        'store', 'summer', 'train', 'sleep', 'prove', 'lone', 'leg', 'exercise', 'wall', 'catch',
        'mount', 'wish', 'sky', 'board', 'joy', 'winter', 'sat', 'written', 'wild', 'instrument',
        'kept', 'glass', 'grass', 'cow', 'job', 'edge', 'sign', 'visit', 'past', 'soft', 'fun',
        'bright', 'gas', 'weather', 'month', 'million', 'bear', 'finish', 'happy', 'hope', 'flower',
        'clothe', 'strange', 'gone', 'jump', 'baby', 'eight', 'village', 'meet', 'root', 'buy',
        'raise', 'solve', 'metal', 'whether', 'push', 'seven', 'paragraph', 'third', 'shall', 'held',
        'hair', 'describe', 'cook', 'floor', 'either', 'result', 'burn', 'hill', 'safe', 'cat',
        'century', 'consider', 'type', 'law', 'bit', 'coast', 'copy', 'phrase', 'silent', 'tall',
        'sand', 'soil', 'roll', 'temperature', 'finger', 'industry', 'value', 'fight', 'lie', 'beat',
        'excite', 'natural', 'view', 'sense', 'ear', 'else', 'quite', 'broke', 'case', 'middle',
        'kill', 'son', 'lake', 'moment', 'scale', 'loud', 'spring', 'observe', 'child', 'straight',
        'consonant', 'nation', 'dictionary', 'milk', 'speed', 'method', 'organ', 'pay', 'age',
        'section', 'dress', 'cloud', 'surprise', 'quiet', 'stone', 'tiny', 'climb', 'cool', 'design',
        'poor', 'lot', 'experiment', 'bottom', 'key', 'iron', 'single', 'stick', 'flat', 'twenty',
        'skin', 'smile', 'crease', 'hole', 'trade', 'melody', 'trip', 'office', 'receive', 'row',
        'mouth', 'exact', 'symbol', 'die', 'least', 'trouble', 'shout', 'except', 'wrote', 'seed',
        'tone', 'join', 'suggest', 'clean', 'break', 'lady', 'yard', 'rise', 'bad', 'blow', 'oil',
        'blood', 'touch', 'grew', 'cent', 'mix', 'team', 'wire', 'cost', 'lost', 'brown', 'wear',
        'garden', 'equal', 'sent', 'choose', 'fell', 'fit', 'flow', 'fair', 'bank', 'collect', 'save',
        'control', 'decimal', 'gentle', 'woman', 'captain', 'practice', 'separate', 'difficult',
        'doctor', 'please', 'protect', 'noon', 'crop', 'modern', 'element', 'hit', 'student', 'corner',
        'party', 'supply', 'whose', 'locate', 'ring', 'character', 'insect', 'caught', 'period',
        'indicate', 'radio', 'spoke', 'atom', 'human', 'history', 'effect', 'electric', 'expect',
        'bone', 'rail', 'imagine', 'provide', 'agree', 'thus', 'gentle', 'woman', 'captain', 'guess',
        'necessary', 'sharp', 'wing', 'create', 'neighbor', 'wash', 'bat', 'rather', 'crowd', 'corn',
        'compare', 'poem', 'string', 'bell', 'depend', 'meat', 'rub', 'tube', 'famous', 'dollar',
        'stream', 'fear', 'sight', 'thin', 'triangle', 'planet', 'hurry', 'chief', 'colony', 'clock',
        'mine', 'tie', 'enter', 'major', 'fresh', 'search', 'send', 'yellow', 'gun', 'allow', 'print',
        'dead', 'spot', 'desert', 'suit', 'current', 'lift', 'rose', 'continue', 'block', 'chart',
        'hat', 'sell'
    ],
    "Portuguese": [
        'que', 'para', 'com', 'não', 'uma', 'por', 'mais', 'dos', 'como', 'mas', 'foi', 'ele', 'das',
        'tem', 'seu', 'sua', 'ser', 'quando', 'muito', 'nos', 'está', 'também', 'pelo', 'pela', 'até',
        'isso', 'ela', 'entre', 'depois', 'sem', 'mesmo', 'aos', 'seus', 'quem', 'nas', 'esse', 'eles',
        'estão', 'você', 'tinha', 'foram', 'essa', 'num', 'nem', 'suas', 'meu', 'minha', 'têm', 'numa',
        'pelos', 'elas', 'havia', 'sejam', 'qual', 'vai', 'ter', 'onde', 'fez', 'agora', 'diz', 'será',
        'lhes', 'pode', 'todos', 'todas', 'talvez', 'seja', 'porque', 'vamos', 'sobre', 'meu', 'meus',
        'mim', 'ainda', 'outro', 'tem', 'vez', 'agora', 'nunca', 'sempre', 'ainda', 'nossos', 'teus',
        'deles', 'delas', 'essas', 'aqueles', 'aquelas', 'isto', 'tudo', 'nada', 'outra', 'pouco',
        'alguns', 'algumas', 'cada', 'saber', 'dizer', 'fazer', 'poder', 'querer', 'ver', 'dar',
        'estar', 'vir', 'ter', 'ficar', 'deixar', 'parecer', 'trazer', 'houver', 'nossos', 'teus',
        'muitas', 'vezes', 'assim', 'mesma', 'assim', 'mesmas', 'outros', 'tanta', 'tanto', 'tantos',
        'quanto', 'quanta', 'quanta', 'quantos', 'pessoas', 'coisas', 'muitos', 'depois', 'deixa',
        'daqui', 'mundo', 'gente', 'coisa', 'alguma', 'outros', 'forma', 'anos', 'tempo', 'qualquer',
        'melhor', 'antes', 'semana', 'meses', 'ano', 'nosso', 'vida', 'trabalho', 'outras', 'parte',
        'mesmo', 'mesma', 'forma', 'casa', 'deveria', 'aqui', 'perguntar', 'diferente', 'acontecer',
        'sentir', 'grande', 'queria', 'ficou', 'necessário', 'importante', 'deveria', 'possível',
        'passar', 'pessoa', 'ver', 'começou', 'parecia', 'sempre', 'dentro', 'durante', 'história',
        'semana', 'lugar', 'você', 'melhor', 'aquilo', 'pontos', 'problema', 'portanto', 'certeza',
        'trabalho', 'portanto', 'necessário', 'impossível', 'talvez', 'primeiro', 'segundo', 'perguntar',
        'melhor', 'sentir', 'grande', 'último', 'grande', 'pequeno', 'disse', 'disseram', 'pequena',
        'daqueles', 'várias', 'conhecer', 'falar', 'ouvir'
    ],
    "Spanish": [
        'que', 'los', 'del', 'las', 'por', 'para', 'con', 'una', 'como', 'más', 'pero', 'sus', 'este',
        'porque', 'esta', 'entre', 'cuando', 'muy', 'sin', 'sobre', 'también', 'hasta', 'hay', 'donde',
        'quien', 'desde', 'todo', 'nos', 'durante', 'todos', 'uno', 'les', 'contra', 'otros', 'ese', 'eso',
        'ante', 'ellos', 'esto', 'antes', 'algunos', 'qué', 'unos', 'otro', 'otras', 'otra', 'tanto', 'esa',
        'estos', 'mucho', 'quienes', 'nada', 'muchos', 'cual', 'poco', 'ella', 'estar', 'estas', 'algunas',
        'algo', 'nosotros', 'mis', 'tus', 'ellas', 'nosotras', 'vosotros', 'vosotras', 'mío', 'mía', 'míos',
        'mías', 'tuyo', 'tuya', 'tuyos', 'tuyas', 'suyo', 'suya', 'suyos', 'suyas', 'nuestro', 'nuestra',
        'nuestros', 'nuestras', 'vuestro', 'vuestra', 'vuestros', 'vuestras', 'esos', 'esas', 'estoy',
        'estás', 'está', 'estamos', 'estáis', 'están', 'esté', 'estés', 'esté', 'estemos', 'estéis',
        'estén', 'estaré', 'estarás', 'estará', 'estaremos', 'estaréis', 'estarán', 'estaría', 'estarías',
        'estaría', 'estaríamos', 'estaríais', 'estarían', 'estaba', 'estabas', 'estaba', 'estábamos',
        'estabais', 'estaban', 'estuve', 'estuviste', 'estuvo', 'estuvimos', 'estuvisteis', 'estuvieron',
        'estuviera', 'estuvieras', 'estuviera', 'estuviéramos', 'estuvierais', 'estuvieran', 'estuviese',
        'estuvieses', 'estuviese', 'estuviésemos', 'estuvieseis', 'estuviesen', 'estando', 'estado',
        'estada', 'estados', 'estadas', 'estad', 'has', 'hemos', 'habéis', 'han', 'haya', 'hayas', 'haya',
        'hayamos', 'hayáis', 'hayan', 'habré', 'habrás', 'habrá', 'habremos', 'habréis', 'habrán', 'habría',
        'habrías', 'habría', 'habríamos', 'habríais', 'habrían', 'había', 'habías', 'había', 'habíamos',
        'habíais', 'habían', 'hube', 'hubiste', 'hubo', 'hubimos', 'hubisteis', 'hubieron', 'hubiera',
        'hubieras', 'hubiera', 'hubiéramos', 'hubierais', 'hubieran', 'hubiese', 'hubieses', 'hubiese',
        'hubiésemos', 'hubieseis', 'hubiesen', 'habiendo', 'habido', 'habida', 'habidos', 'habidas', 'soy',
        'eres', 'somos', 'sois', 'son', 'sea', 'seas', 'sea', 'seamos', 'seáis', 'sean', 'seré', 'serás',
        'será', 'seremos', 'seréis', 'serán', 'sería', 'serías', 'sería', 'seríamos', 'seríais', 'serían',
        'era', 'eras', 'era', 'éramos', 'erais', 'eran', 'fui', 'fuiste', 'fue', 'fuimos', 'fuisteis',
        'fueron', 'fuera', 'fueras', 'fuera', 'fuéramos', 'fuerais', 'fueran', 'fuese', 'fueses', 'fuese',
        'fuésemos', 'fueseis', 'fuesen', 'siendo', 'sido', 'tengo', 'tienes', 'tiene', 'tenemos', 'tenéis',
        'tienen', 'tenga', 'tengas', 'tenga', 'tengamos', 'tengáis', 'tengan', 'tendré', 'tendrás', 'tendrá',
        'tendremos', 'tendréis', 'tendrán', 'tendría', 'tendrías', 'tendría', 'tendríamos', 'tendríais',
        'tendrían', 'tenía', 'tenías', 'tenía', 'teníamos', 'teníais', 'tenían', 'tuve', 'tuviste', 'tuvo',
        'tuvimos', 'tuvisteis', 'tuvieron', 'tuviera', 'tuvieras', 'tuviera', 'tuviéramos', 'tuvierais',
        'tuvieran', 'tuviese', 'tuvieses', 'tuviese', 'tuviésemos', 'tuvieseis', 'tuviesen', 'teniendo',
        'tenido', 'tenida', 'tenidos', 'tenidas', 'tened'
    ],
    "Czech": [
        'aber', 'alle', 'allem', 'allen', 'aller', 'alles', 'als', 'also', 'andere', 'anderen', 'anderer',
        'anderes', 'andern', 'andernfalls', 'auch', 'auf', 'aus', 'bei', 'bin', 'bis', 'bist', 'damit',
        'dann', 'darum', 'das', 'dass', 'dasselbe', 'davon', 'dazu', 'daß', 'dein', 'deine', 'dem', 'den',
        'denn', 'der', 'derer', 'derselbe', 'derselben', 'des', 'desselben', 'dessen', 'dich', 'die',
        'dies', 'diese', 'dieselbe', 'dieselben', 'diesem', 'diesen', 'dieser', 'dieses', 'dir', 'doch',
        'dort', 'durch', 'ein', 'eine', 'einem', 'einen', 'einer', 'eines', 'einig', 'einige', 'einigem',
        'einigen', 'einiger', 'einiges', 'einmal', 'etwas', 'euch', 'euer', 'eure', 'für', 'gegen', 'gewesen',
        'hab', 'habe', 'haben', 'hat', 'hatte', 'hatten', 'hier', 'hin', 'hinter', 'ich', 'ihm', 'ihn', 'ihnen',
        'ihr', 'ihre', 'indem', 'ins', 'ist', 'jede', 'jedem', 'jeden', 'jeder', 'jedes', 'jene', 'jenem',
        'jenen', 'jener', 'jenes', 'jetzt', 'kann', 'kein', 'keine', 'keinem', 'keinen', 'keiner', 'keines',
        'können', 'könnte', 'machen', 'man', 'manche', 'manchem', 'manchen', 'mancher', 'manches', 'mein',
        'meine', 'mit', 'muss', 'musste', 'nach', 'nicht', 'nichts', 'noch', 'nun', 'nur', 'oder', 'ohne',
        'sehr', 'sein', 'seine', 'seinem', 'seinen', 'seiner', 'seines', 'selbst', 'sich', 'sie', 'sind',
        'solche', 'solchem', 'solchen', 'solcher', 'solches', 'soll', 'sollte', 'sondern', 'sonst', 'über',
        'und', 'uns', 'unse', 'unsem', 'unsen', 'unser', 'unses', 'unter', 'viel', 'vom', 'von', 'vor', 'war',
        'waren', 'warst', 'was', 'weg', 'weil', 'weiter', 'welche', 'welchem', 'welchen', 'welcher', 'welches',
        'wenn', 'werde', 'werden', 'wie', 'wieder', 'will', 'wir', 'wird', 'wirst', 'wollen', 'wollte', 'würde',
        'würden', 'zum', 'zur', 'zwar', 'zwischen'
    ],
    "German": [
        'aby', 'ale', 'ani', 'asi', 'být', 'bude', 'byl', 'byla', 'byli', 'bylo', 'byly', 'člověk', 'dát',
        'dnes', 'dobrý', 'docela', 'dvě', 'jak', 'jako', 'její', 'jejich', 'jemu', 'jen', 'ještě',
        'jeho', 'jich', 'jím', 'jsem', 'jsi', 'jsme', 'jsou', 'kam', 'kdy', 'když', 'kdo', 'konec',
        'která', 'které', 'který', 'když', 'když', 'kdo', 'kde', 'kdy', 'lidé', 'máte', 'mezi', 'mít',
        'mne', 'mnou', 'moc', 'mohl', 'moje', 'můj', 'musí', 'nad', 'nám', 'námi', 'náš', 'nebo', 'něco',
        'nějak', 'někde', 'někdo', 'něm', 'než', 'nic', 'něj', 'němu', 'nás', 'náš', 'nový', 'nyní', 'ode',
        'ona', 'ony', 'pod', 'pokud', 'pro', 'prostě', 'proto', 'protože', 'první', 'před', 'přes', 'při',
        'před', 'příliš', 'své', 'svůj', 'tady', 'tak', 'takhle', 'taky', 'tam', 'tato', 'tato', 'tebe',
        'tebou', 'tedy', 'ten', 'tento', 'tobě', 'toho', 'tohle', 'tom', 'tomto', 'tomu', 'tuto', 'tvé',
        'tvůj', 'tyto', 'vám', 'vámi', 'váš', 'více', 'však', 'všechen', 'vždy', 'zda', 'zítra', 'bez',
        'během', 'blízko', 'bych', 'bychom', 'byste', 'cesta', 'což', 'často', 'čas', 'časem', 'často',
        'čemu', 'čím', 'dál', 'dle', 'dnes', 'dobře', 'docela', 'dole', 'dolů', 'dříve', 'hlavně', 'hodně',
        'hodinu', 'jak', 'jako', 'jaký', 'jeho', 'její', 'jejich', 'jemu', 'jen', 'ještě', 'jich', 'jím',
        'jsem', 'jsi', 'jsme', 'jsou', 'jít', 'každý', 'kde', 'kdo', 'kdy', 'když', 'kolik', 'kolem', 'konce',
        'která', 'které', 'který', 'kteří', 'když', 'mám', 'málo', 'máme', 'máš', 'měli', 'mezi', 'mít',
        'mně', 'moc', 'moje', 'můj', 'musí', 'nad', 'nám', 'námi', 'náš', 'nebo', 'něco', 'nějak', 'někde',
        'někdo', 'němu', 'než', 'nic', 'nás', 'náš', 'než', 'nic', 'nás', 'náš', 'nový', 'ode', 'ona', 'ony',
        'pod', 'pokud', 'pro', 'prostě', 'proto', 'protože', 'před', 'přes', 'při', 'příliš', 'před', 'své',
        'svůj', 'tady', 'tak', 'takhle', 'taky', 'tam', 'tato', 'teď', 'tebe', 'tebou', 'tedy', 'ten', 'tento',
        'tobě', 'toho', 'tohle', 'tom', 'tomto', 'tomu', 'tuto', 'tvé', 'tvůj', 'tyto', 'vám', 'vámi', 'váš',
        'více', 'však', 'vše', 'všechno', 'vždy', 'zítra', 'zase', 'zpátky', 'zřejmě'
    ],
    "French": [
        'abord', 'afin', 'aie', 'ailleurs', 'ainsi', 'ait', 'allaient', 'allo', 'allô', 'allons', 'après',
        'assez', 'attendu', 'aucun', 'aucune', 'aujourd', "aujourd'hui", 'auquel', 'aura', 'auront', 'aussi',
        'autre', 'autres', 'aux', 'auxquelles', 'auxquels', 'avaient', 'avais', 'avait', 'avant', 'avec',
        'avoir', 'ayant', 'bah', 'beaucoup', 'bien', 'bigre', 'boum', 'bravo', 'brrr', 'car', 'ceci', 'cela',
        'celle', 'celle-ci', 'celle-là', 'celles', 'celles-ci', 'celles-là', 'celui', 'celui-ci', 'celui-là',
        'cent', 'cependant', 'certain', 'certaine', 'certaines', 'certains', 'ces', 'cet', 'cette', 'ceux',
        'ceux-ci', 'ceux-là', 'chacun', 'chaque', 'cher', 'chers', 'chez', 'chiche', 'chut', 'cinq',
        'cinquantaine', 'cinquante', 'cinquantième', 'cinquième', 'clac', 'clic', 'combien', 'comme',
        'comment', 'compris', 'concernant', 'contre', 'couic', 'crac', 'dans', 'dehors', 'delà', 'depuis',
        'derrière', 'des', 'dès', 'désormais', 'desquelles', 'desquels', 'dessous', 'dessus', 'deux',
        'deuxième', 'deuxièmement', 'devant', 'devers', 'devra', 'différent', 'différente', 'différentes',
        'différents', 'dire', 'divers', 'diverse', 'diverses', 'dix', 'dix-huit', 'dixième', 'dix-neuf',
        'dix-sept', 'doit', 'doivent', 'donc', 'dont', 'douze', 'douzième', 'dring', 'duquel', 'durant',
        'effet', 'elle', 'elle-même', 'elles', 'elles-mêmes', 'encore', 'entre', 'envers', 'environ', 'est',
        'etant', 'étaient', 'étais', 'était', 'étant', 'etc', 'été', 'etre', 'être', 'euh', 'eux', 'eux-mêmes',
        'excepté', 'façon', 'fais', 'faisaient', 'faisant', 'fait', 'feront', 'flac', 'floc', 'font', 'gens',
        'hein', 'hélas', 'hem', 'hep', 'holà', 'hop', 'hormis', 'hors', 'hou', 'houp', 'hue', 'hui', 'huit',
        'huitième', 'hum', 'hurrah', 'ils', 'importe', 'jusqu', 'jusque', 'laquelle', 'las', 'lequel', 'les',
        'lès', 'lesquelles', 'lesquels', 'leur', 'leurs', 'longtemps', 'lors', 'lorsque', 'lui', 'lui-même',
        'maint', 'mais', 'malgré', 'même', 'mêmes', 'merci', 'mes', 'mien', 'mienne', 'miennes', 'miens', 'mille',
        'mince', 'moi', 'moi-même', 'moindres', 'moins', 'mon', 'moyennant', 'néanmoins', 'neuf', 'neuvième',
        'nombreuses', 'nombreux', 'non', 'nos', 'notre', 'nôtre', 'nôtres', 'nous', 'nous-mêmes', 'nul', 'ohé',
        'olé', 'ollé', 'ont', 'onze', 'onzième', 'ore', 'ouf', 'ouias', 'oust', 'ouste', 'outre', 'paf', 'pan',
        'par', 'parce', 'parfois', 'parle', 'parlent', 'parler', 'parmi', 'parsemblable', 'partant', 'particulier',
        'particulière', 'particulièrement', 'pas', 'passé', 'pendant', 'personne', 'peu', 'peut', 'peuvent', 'peux',
        'pff', 'pfft', 'pfut', 'pif', 'plein', 'plouf', 'plus', 'plusieurs', 'plutôt', 'pouah', 'pour', 'pourquoi',
        'premier', 'première', 'premièrement', 'près', 'proche', 'psitt', 'puis', 'puisque', 'pur', 'pure', 'quand',
        'quant', 'quanta', 'quant-à-soi', 'quarante', 'quatorze', 'quatre', 'quatre-vingt', 'quatrième',
        'quatrièmement', 'que', 'quel', 'quelle', 'quelles', "quelqu'un", 'quelque', 'quelques', 'quels',
        'qui', 'quiconque', 'quinze', 'quoi', 'quoique', 'revoici', 'revoilà', 'rien', 'sacrebleu', 'sans',
        'sapristi', 'sauf', 'seize', 'selon', 'sept', 'septième', 'sera', 'seront', 'ses', 'sien', 'sienne',
        'siennes', 'siens', 'sinon', 'six', 'sixième', 'soi', 'soi-même', 'soit', 'son', 'sont', 'sous',
        'stop', 'suis', 'suivant', 'sur', 'tac', 'tant', 'tel', 'telle', 'tellement', 'telles', 'tels',
        'tenant', 'tes', 'tic', 'tien', 'tienne', 'tiennes', 'tiens', 'toc', 'toi', 'toi-même', 'ton',
        'touchant', 'toujours', 'tous', 'tout', 'toute', 'toutes', 'treize', 'trente', 'très', 'trois',
        'troisième', 'troisièmement', 'trop', 'tsoin', 'tsouin', 'une', 'unes', 'uns', 'vais', 'vas',
        'vers', 'via', 'vif', 'vifs', 'vingt', 'vivat', 'vive', 'vives', 'vlan', 'voici', 'voilà', 'vont',
        'vos', 'votre', 'vôtre', 'vôtres', 'vous', 'vous-mêmes', 'zut'
    ]
}

"""
# To filtering manually:
filtered = [word for word in lang["fr"] if len(word) > 2]
print(filtered)
"""

